[package]
name = "express_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
hyper = { version = "1.6.0", features = ["full"] }
http-body-util = "0.1.3"
hyper-util = {version = "0.1.11", features = ["tokio"]}
tokio = {version = "1.44.2", features = ["full"]}
serde = "1.0.219"
serde_json = "1.0.140"
bytes = "1.10.1"
url = "2.5.4"
once_cell = "1.21.3"
itoa = "1.0.15"
mime_guess = "2.0.5"
tokio-util = "0.7.15"
futures-core = "0.3.31"
futures-util = "0.3.31"
lru = "0.14.0"
infer = "0.19.0"
thiserror = "2.0.12"
log = "0.4.27"
env_logger = "0.11.8"
local-ip-address = "0.6.5"
radix_trie = "0.2.1"
matchthem = "0.0.1"
