[package]
name = "express_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
hyper = { version = "1.6.0", features = ["full"] }
http-body-util = "0.1.3"
hyper-util = {version = "0.1.11", features = ["tokio"]}
tokio = {version = "1.44.2", features = ["full"]}
serde = "1.0.219"
serde_json = "1.0.140"
bytes = "1.10.1"
